version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    restart: always

networks:
  default:
    driver: bridge
